# Generated by Django 6.0.6 on 2026-06-18 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('region', models.CharField(choices=[('tanger-tetouan', 'Tanger-Tétouan-Al Hoceïma'), ('oriental', "L'Oriental"), ('fes-meknes', 'Fès-Meknès'), ('rabat-sale', 'Rabat-Salé-Kénitra'), ('beni-mellal', 'Béni Mellal-Khénifra'), ('casablanca', 'Casablanca-Settat'), ('marrakech', 'Marrakech-Safi'), ('draa-tafilalet', 'Drâa-Tafilalet'), ('souss-massa', 'Souss-Massa'), ('guelmim', 'Guelmim-Oued Noun'), ('laayoune', 'Laâyoune-Sakia El Hamra'), ('dakhla', 'Dakhla-Oued Ed Dahab')], max_length=50)),
                ('ville', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('surface', models.DecimalField(decimal_places=2, help_text='Surface en hectares', max_digits=10)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en MAD', max_digits=14)),
                ('type_culture', models.CharField(choices=[('cereales', 'Céréales (blé, orge, maïs)'), ('maraichage', 'Maraîchage'), ('arboriculture', 'Arboriculture fruitière'), ('olivier', 'Olivier'), ('agrumes', 'Agrumes'), ('viticulture', 'Viticulture'), ('elevage', 'Élevage / Prairie'), ('polyculture', 'Polyculture'), ('autre', 'Autre')], max_length=30)),
                ('type_titre_foncier', models.CharField(choices=[('melkia', 'Melkia (propriété privée)'), ('collectif', 'Collectif / Tribal'), ('domanial', 'Domanial'), ('en_cours', "En cours d'immatriculation")], max_length=20)),
                ('acces_eau', models.BooleanField(default=False, verbose_name="Accès à l'eau")),
                ('acces_route', models.BooleanField(default=False, verbose_name='Accès route')),
                ('electricite', models.BooleanField(default=False, verbose_name='Électricité')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_attente', 'En attente'), ('desactivee', 'Désactivée')], default='en_attente', max_length=15)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AnnoncePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.annonce')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
