# Generated by Django 6.0.6 on 2026-06-20 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_favori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_jours', models.PositiveSmallIntegerField(choices=[(7, '7 jours'), (14, '14 jours'), (30, '30 jours')])),
                ('prix_paye', models.DecimalField(decimal_places=2, max_digits=8)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de paiement'), ('actif', 'Actif'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='en_attente', max_length=15)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='listings.annonce')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Boost',
                'verbose_name_plural': 'Boosts',
                'ordering': ['-date_commande'],
            },
        ),
    ]
