# Generated by Django 6.0.6 on 2026-06-20 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_boost'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_vues', to='listings.annonce')),
            ],
            options={
                'verbose_name': 'Vue (historique)',
                'verbose_name_plural': 'Vues (historique)',
                'indexes': [models.Index(fields=['annonce', 'date'], name='listings_vu_annonce_f3f917_idx')],
            },
        ),
    ]
