# Generated by Django 6.0.6 on 2026-06-21 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_vueannonce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boost',
        ),
    ]
